language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
script:
  - dotnet restore
  - dotnet build
  - cd Test && dotnet test
  - cd .. 
  - cd tss-tool-com
  - nvm use v6.9.1
  - npm install aurelia-cli -g
  - au build --watch
